/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author xian_w
 */
public class SignupPage extends javax.swing.JFrame {

    /**
     * Creates new form SignupPage
     */
    public SignupPage() {
        initComponents();
    }
    
    //method to insert values into user table
    public void insetSignupDetails(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        String email = txt_email.getText();
        String contact = txt_contact.getText();
       
        try{
            Connection con = DBConnection.getConnection();
            String sql = "insert into users(name,password,email,contact) values(?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);
            
            pst.setString(1,name);
            pst.setString(2,pwd);
            pst.setString(3,email);
            pst.setString(4,contact);
           
            
            int updateRowCount =  pst.executeUpdate();
            if(updateRowCount > 0){
                JOptionPane.showMessageDialog(this,"Sign up successfully.");
                LoginPage page = new LoginPage();
                page.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Fail to register.");
            }
            
    }catch (Exception e){
          e.printStackTrace();

     }
    }
    
    //validation
    public boolean validateSignup(){
        String name = txt_username.getText();
        String pwd = txt_password.getText();
        String email = txt_email.getText();
        String contact = txt_contact.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(this, "please enter username.");
            return false;
        }else if(pwd.equals("")){
             JOptionPane.showMessageDialog(this, "please enter password.");
            return false;
        }else if(email.equals("") || !email.matches("^.+@.+\\..+$"))
        {
             JOptionPane.showMessageDialog(this, "please enter valid email.");
            return false;
        }else if(contact.equals("")){
             JOptionPane.showMessageDialog(this, "please enter contact number.");
            return false;
    }
     return true;
    }
        
     //check duplicate user
     public boolean checkDupliacateUser(){
         String name = txt_username.getText();
         boolean isExist = false;
         try{
             Connection con = DBConnection.getConnection();
             String sql = "select * from users where name = ?";
             PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1, name);
             
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                isExist = true;
            }else{
                isExist = false;
            }   
         }catch(Exception e){
             e.printStackTrace();;
         }
         return isExist;
     }
         

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_password = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_email = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCTextField6 = new app.bolivia.swing.JCTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jCTextField7 = new app.bolivia.swing.JCTextField();
        jCTextField8 = new app.bolivia.swing.JCTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jCTextField9 = new app.bolivia.swing.JCTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jCTextField10 = new app.bolivia.swing.JCTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jCTextField11 = new app.bolivia.swing.JCTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jCTextField12 = new app.bolivia.swing.JCTextField();
        jCTextField13 = new app.bolivia.swing.JCTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jCTextField14 = new app.bolivia.swing.JCTextField();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jCTextField15 = new app.bolivia.swing.JCTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jCTextField16 = new app.bolivia.swing.JCTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jCTextField17 = new app.bolivia.swing.JCTextField();
        jCTextField18 = new app.bolivia.swing.JCTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jCTextField19 = new app.bolivia.swing.JCTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jCTextField20 = new app.bolivia.swing.JCTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jCTextField22 = new app.bolivia.swing.JCTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jCTextField23 = new app.bolivia.swing.JCTextField();
        jCTextField24 = new app.bolivia.swing.JCTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jCTextField25 = new app.bolivia.swing.JCTextField();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jCTextField26 = new app.bolivia.swing.JCTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jCTextField27 = new app.bolivia.swing.JCTextField();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jCTextField28 = new app.bolivia.swing.JCTextField();
        jCTextField29 = new app.bolivia.swing.JCTextField();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jCTextField30 = new app.bolivia.swing.JCTextField();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jCTextField31 = new app.bolivia.swing.JCTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jCTextField32 = new app.bolivia.swing.JCTextField();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jCTextField33 = new app.bolivia.swing.JCTextField();
        jCTextField34 = new app.bolivia.swing.JCTextField();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jCTextField35 = new app.bolivia.swing.JCTextField();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jCTextField36 = new app.bolivia.swing.JCTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jCTextField37 = new app.bolivia.swing.JCTextField();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jCTextField38 = new app.bolivia.swing.JCTextField();
        jCTextField39 = new app.bolivia.swing.JCTextField();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jCTextField40 = new app.bolivia.swing.JCTextField();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jCTextField41 = new app.bolivia.swing.JCTextField();
        jLabel112 = new javax.swing.JLabel();
        jCTextField42 = new app.bolivia.swing.JCTextField();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        txt_contact = new app.bolivia.swing.JCTextField();
        rSMaterialButtonCircle1 = new necesario.RSMaterialButtonCircle();
        rSMaterialButtonCircle2 = new necesario.RSMaterialButtonCircle();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Toppan Bunkyu Mincho", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Advance Library");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 30));

        jLabel2.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Developer");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("STIX Two Text", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("Lionme");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 30));

        jLabel4.setFont(new java.awt.Font("STSong", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 204));
        jLabel4.setText("Welcom to ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signup-library-icon.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 740));

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 30, 40));

        jLabel8.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Username:");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, 40));

        jLabel9.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 255, 255));
        jLabel9.setText("Create New Account");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 40));

        txt_username.setBackground(new java.awt.Color(102, 102, 255));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txt_username.setPlaceholder("Enter username ....");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel4.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 40));

        jLabel12.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secure_50px.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 40));

        txt_password.setBackground(new java.awt.Color(102, 102, 255));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txt_password.setPlaceholder("Enter password ....");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        jPanel4.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Password:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, 40));

        txt_email.setBackground(new java.awt.Color(102, 102, 255));
        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_email.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txt_email.setPlaceholder("Enter email ....");
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel4.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        jLabel15.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 255, 255));
        jLabel15.setText("Email:");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, 40));

        jLabel16.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Secured_Letter_50px.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 40));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 255, 255));
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 255, 255));
        jLabel20.setText("Sign Up Here !");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 255, 255));
        jLabel21.setText("Username:");
        jPanel5.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel22.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 255, 255));
        jLabel22.setText("Create New Account");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField6.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField6.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField6.setPlaceholder("Enter username ....");
        jCTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField6ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel23.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 255, 255));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel24.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 255, 255));
        jLabel24.setText("Username:");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel25.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField7.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField7.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField7.setPlaceholder("Enter username ....");
        jCTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField7ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField8.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField8.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField8.setPlaceholder("Enter username ....");
        jCTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField8ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel26.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 255, 255));
        jLabel26.setText("Username:");
        jPanel5.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel27.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField9.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField9.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField9.setPlaceholder("Enter username ....");
        jCTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField9ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel28.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 255, 255));
        jLabel28.setText("Username:");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel29.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 255, 255));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel30.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 255, 255));
        jLabel30.setText("Username:");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel31.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel5.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField10.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField10.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField10.setPlaceholder("Enter username ....");
        jCTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField10ActionPerformed(evt);
            }
        });
        jPanel5.add(jCTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jPanel6.setBackground(new java.awt.Color(102, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 255, 255));
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel33.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 255, 255));
        jLabel33.setText("Sign Up Here !");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel34.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 255, 255));
        jLabel34.setText("Username:");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel35.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 255, 255));
        jLabel35.setText("Create New Account");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField11.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField11.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField11.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField11.setPlaceholder("Enter username ....");
        jCTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField11ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel36.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 255, 255));
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel37.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 255, 255));
        jLabel37.setText("Username:");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel38.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 255, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField12.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField12.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField12.setPlaceholder("Enter username ....");
        jCTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField12ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField13.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField13.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField13.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField13.setPlaceholder("Enter username ....");
        jCTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField13ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel39.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 255, 255));
        jLabel39.setText("Username:");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel40.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 255, 255));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField14.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField14.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField14.setPlaceholder("Enter username ....");
        jCTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField14ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel41.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 255, 255));
        jLabel41.setText("Username:");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel42.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 255, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel43.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 255, 255));
        jLabel43.setText("Username:");
        jPanel6.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel44.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 255, 255));
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel6.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField15.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField15.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField15.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField15.setPlaceholder("Enter username ....");
        jCTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField15ActionPerformed(evt);
            }
        });
        jPanel6.add(jCTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 255, 255));
        jPanel7.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 255, 255));
        jLabel46.setText("Sign Up Here !");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel47.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(204, 255, 255));
        jLabel47.setText("Username:");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel48.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(204, 255, 255));
        jLabel48.setText("Create New Account");
        jPanel7.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField16.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField16.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField16.setPlaceholder("Enter username ....");
        jCTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField16ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel49.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 255, 255));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel50.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 255, 255));
        jLabel50.setText("Username:");
        jPanel7.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel51.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 255, 255));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField17.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField17.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField17.setPlaceholder("Enter username ....");
        jCTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField17ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField18.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField18.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField18.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField18.setPlaceholder("Enter username ....");
        jCTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField18ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel52.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 255, 255));
        jLabel52.setText("Username:");
        jPanel7.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel53.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 255, 255));
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField19.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField19.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField19.setPlaceholder("Enter username ....");
        jCTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField19ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel54.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 255, 255));
        jLabel54.setText("Username:");
        jPanel7.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel55.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 255, 255));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel56.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(204, 255, 255));
        jLabel56.setText("Username:");
        jPanel7.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel57.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(204, 255, 255));
        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel7.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField20.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField20.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField20.setPlaceholder("Enter username ....");
        jCTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField20ActionPerformed(evt);
            }
        });
        jPanel7.add(jCTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jLabel59.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(204, 255, 255));
        jPanel4.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jPanel8.setBackground(new java.awt.Color(102, 102, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(204, 255, 255));
        jPanel8.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel61.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel61.setForeground(new java.awt.Color(204, 255, 255));
        jLabel61.setText("Sign Up Here !");
        jPanel8.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel62.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel62.setForeground(new java.awt.Color(204, 255, 255));
        jLabel62.setText("Username:");
        jPanel8.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel63.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(204, 255, 255));
        jLabel63.setText("Create New Account");
        jPanel8.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField22.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField22.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField22.setPlaceholder("Enter username ....");
        jCTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField22ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel64.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(204, 255, 255));
        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel65.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(204, 255, 255));
        jLabel65.setText("Username:");
        jPanel8.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel66.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 255, 255));
        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField23.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField23.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField23.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField23.setPlaceholder("Enter username ....");
        jCTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField23ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField24.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField24.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField24.setPlaceholder("Enter username ....");
        jCTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField24ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel67.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 255, 255));
        jLabel67.setText("Username:");
        jPanel8.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel68.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 255, 255));
        jLabel68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField25.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField25.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField25.setPlaceholder("Enter username ....");
        jCTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField25ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel69.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(204, 255, 255));
        jLabel69.setText("Username:");
        jPanel8.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel70.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 255, 255));
        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel71.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(204, 255, 255));
        jLabel71.setText("Username:");
        jPanel8.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel72.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 255, 255));
        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField26.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField26.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField26.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField26.setPlaceholder("Enter username ....");
        jCTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField26ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(204, 255, 255));
        jPanel9.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel74.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(204, 255, 255));
        jLabel74.setText("Sign Up Here !");
        jPanel9.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel75.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(204, 255, 255));
        jLabel75.setText("Username:");
        jPanel9.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel76.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 255, 255));
        jLabel76.setText("Create New Account");
        jPanel9.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField27.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField27.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField27.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField27.setPlaceholder("Enter username ....");
        jCTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField27ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel77.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(204, 255, 255));
        jLabel77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel78.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(204, 255, 255));
        jLabel78.setText("Username:");
        jPanel9.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel79.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 255, 255));
        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField28.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField28.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField28.setPlaceholder("Enter username ....");
        jCTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField28ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField29.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField29.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField29.setPlaceholder("Enter username ....");
        jCTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField29ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel80.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(204, 255, 255));
        jLabel80.setText("Username:");
        jPanel9.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel81.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(204, 255, 255));
        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField30.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField30.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField30.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField30.setPlaceholder("Enter username ....");
        jCTextField30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField30ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel82.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(204, 255, 255));
        jLabel82.setText("Username:");
        jPanel9.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel83.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(204, 255, 255));
        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel84.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(204, 255, 255));
        jLabel84.setText("Username:");
        jPanel9.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel85.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel85.setForeground(new java.awt.Color(204, 255, 255));
        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel9.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField31.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField31.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField31.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField31.setPlaceholder("Enter username ....");
        jCTextField31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField31ActionPerformed(evt);
            }
        });
        jPanel9.add(jCTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jPanel10.setBackground(new java.awt.Color(102, 102, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel86.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(204, 255, 255));
        jPanel10.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel87.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel87.setForeground(new java.awt.Color(204, 255, 255));
        jLabel87.setText("Sign Up Here !");
        jPanel10.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel88.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel88.setForeground(new java.awt.Color(204, 255, 255));
        jLabel88.setText("Username:");
        jPanel10.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel89.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel89.setForeground(new java.awt.Color(204, 255, 255));
        jLabel89.setText("Create New Account");
        jPanel10.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField32.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField32.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField32.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField32.setPlaceholder("Enter username ....");
        jCTextField32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField32ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel90.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(204, 255, 255));
        jLabel90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel91.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(204, 255, 255));
        jLabel91.setText("Username:");
        jPanel10.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel92.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(204, 255, 255));
        jLabel92.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField33.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField33.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField33.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField33.setPlaceholder("Enter username ....");
        jCTextField33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField33ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField34.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField34.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField34.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField34.setPlaceholder("Enter username ....");
        jCTextField34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField34ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel93.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel93.setForeground(new java.awt.Color(204, 255, 255));
        jLabel93.setText("Username:");
        jPanel10.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel94.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(204, 255, 255));
        jLabel94.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField35.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField35.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField35.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField35.setPlaceholder("Enter username ....");
        jCTextField35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField35ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel95.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(204, 255, 255));
        jLabel95.setText("Username:");
        jPanel10.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel96.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(204, 255, 255));
        jLabel96.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel97.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(204, 255, 255));
        jLabel97.setText("Username:");
        jPanel10.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel98.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(204, 255, 255));
        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel10.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField36.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField36.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField36.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField36.setPlaceholder("Enter username ....");
        jCTextField36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField36ActionPerformed(evt);
            }
        });
        jPanel10.add(jCTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel11.setBackground(new java.awt.Color(102, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(204, 255, 255));
        jPanel11.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, 40));

        jLabel100.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel100.setForeground(new java.awt.Color(204, 255, 255));
        jLabel100.setText("Sign Up Here !");
        jPanel11.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        jLabel101.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(204, 255, 255));
        jLabel101.setText("Username:");
        jPanel11.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, 40));

        jLabel102.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(204, 255, 255));
        jLabel102.setText("Create New Account");
        jPanel11.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        jCTextField37.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField37.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField37.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField37.setPlaceholder("Enter username ....");
        jCTextField37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField37ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel103.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel103.setForeground(new java.awt.Color(204, 255, 255));
        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        jLabel104.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel104.setForeground(new java.awt.Color(204, 255, 255));
        jLabel104.setText("Username:");
        jPanel11.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel105.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(204, 255, 255));
        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField38.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField38.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField38.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField38.setPlaceholder("Enter username ....");
        jCTextField38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField38ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jCTextField39.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField39.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField39.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField39.setPlaceholder("Enter username ....");
        jCTextField39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField39ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel106.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(204, 255, 255));
        jLabel106.setText("Username:");
        jPanel11.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, 40));

        jLabel107.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(204, 255, 255));
        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));

        jCTextField40.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField40.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField40.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField40.setPlaceholder("Enter username ....");
        jCTextField40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField40ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel108.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(204, 255, 255));
        jLabel108.setText("Username:");
        jPanel11.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel109.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(204, 255, 255));
        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jLabel110.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel110.setForeground(new java.awt.Color(204, 255, 255));
        jLabel110.setText("Username:");
        jPanel11.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jLabel111.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel111.setForeground(new java.awt.Color(204, 255, 255));
        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel11.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField41.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField41.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField41.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField41.setPlaceholder("Enter username ....");
        jCTextField41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField41ActionPerformed(evt);
            }
        });
        jPanel11.add(jCTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jLabel112.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel112.setForeground(new java.awt.Color(204, 255, 255));
        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel8.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, 40));

        jCTextField42.setBackground(new java.awt.Color(102, 102, 255));
        jCTextField42.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jCTextField42.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        jCTextField42.setPlaceholder("Enter username ....");
        jCTextField42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextField42ActionPerformed(evt);
            }
        });
        jPanel8.add(jCTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        jLabel113.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(204, 255, 255));
        jLabel113.setText("Username:");
        jPanel8.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 40));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 390, 760));

        jLabel114.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel114.setForeground(new java.awt.Color(204, 255, 255));
        jLabel114.setText("Contact:");
        jPanel4.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, -1, 40));

        jLabel115.setFont(new java.awt.Font("Mukta Mahee", 0, 17)); // NOI18N
        jLabel115.setForeground(new java.awt.Color(204, 255, 255));
        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Google_Mobile_50px.png"))); // NOI18N
        jPanel4.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, 40));

        txt_contact.setBackground(new java.awt.Color(102, 102, 255));
        txt_contact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txt_contact.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        txt_contact.setPlaceholder("Enter contact no ....");
        txt_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contactActionPerformed(evt);
            }
        });
        jPanel4.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 102, 102));
        rSMaterialButtonCircle1.setText("LOGIN");
        rSMaterialButtonCircle1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonCircle1MouseClicked(evt);
            }
        });
        jPanel4.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 680, 250, 40));

        rSMaterialButtonCircle2.setBackground(new java.awt.Color(51, 51, 255));
        rSMaterialButtonCircle2.setText("SIGNUP");
        rSMaterialButtonCircle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonCircle2ActionPerformed(evt);
            }
        });
        jPanel4.add(rSMaterialButtonCircle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 250, 50));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 255, 255));
        jLabel11.setText("Sign Up Here !");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 390, 740));

        setSize(new java.awt.Dimension(1170, 740));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jCTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField11ActionPerformed

    private void jCTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField12ActionPerformed

    private void jCTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField13ActionPerformed

    private void jCTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField14ActionPerformed

    private void jCTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField15ActionPerformed

    private void jCTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField16ActionPerformed

    private void jCTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField17ActionPerformed

    private void jCTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField18ActionPerformed

    private void jCTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField19ActionPerformed

    private void jCTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField20ActionPerformed

    private void jCTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField22ActionPerformed

    private void jCTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField23ActionPerformed

    private void jCTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField24ActionPerformed

    private void jCTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField25ActionPerformed

    private void jCTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField26ActionPerformed

    private void jCTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField27ActionPerformed

    private void jCTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField28ActionPerformed

    private void jCTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField29ActionPerformed

    private void jCTextField30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField30ActionPerformed

    private void jCTextField31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField31ActionPerformed

    private void jCTextField32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField32ActionPerformed

    private void jCTextField33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField33ActionPerformed

    private void jCTextField34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField34ActionPerformed

    private void jCTextField35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField35ActionPerformed

    private void jCTextField36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField36ActionPerformed

    private void jCTextField37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField37ActionPerformed

    private void jCTextField38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField38ActionPerformed

    private void jCTextField39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField39ActionPerformed

    private void jCTextField40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField40ActionPerformed

    private void jCTextField41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField41ActionPerformed

    private void jCTextField42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField42ActionPerformed

    private void txt_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contactActionPerformed

    private void rSMaterialButtonCircle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle2ActionPerformed
        // TODO add your handling code here:
        if(validateSignup()){
           if(checkDupliacateUser() == true){
               JOptionPane.showMessageDialog(this, "The user already exists.");
           }
           else{
               insetSignupDetails();
           }    
      
        } 
            
      
    }//GEN-LAST:event_rSMaterialButtonCircle2ActionPerformed

    private void jCTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField10ActionPerformed

    private void jCTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField9ActionPerformed

    private void jCTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField8ActionPerformed

    private void jCTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField7ActionPerformed

    private void jCTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextField6ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
        if(checkDupliacateUser() == true)
            JOptionPane.showMessageDialog(this, "The user already exists.");
    }//GEN-LAST:event_txt_usernameFocusLost

    private void rSMaterialButtonCircle1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonCircle1MouseClicked
        // TODO add your handling code here:
        LoginPage page = new LoginPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSMaterialButtonCircle1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField jCTextField10;
    private app.bolivia.swing.JCTextField jCTextField11;
    private app.bolivia.swing.JCTextField jCTextField12;
    private app.bolivia.swing.JCTextField jCTextField13;
    private app.bolivia.swing.JCTextField jCTextField14;
    private app.bolivia.swing.JCTextField jCTextField15;
    private app.bolivia.swing.JCTextField jCTextField16;
    private app.bolivia.swing.JCTextField jCTextField17;
    private app.bolivia.swing.JCTextField jCTextField18;
    private app.bolivia.swing.JCTextField jCTextField19;
    private app.bolivia.swing.JCTextField jCTextField20;
    private app.bolivia.swing.JCTextField jCTextField22;
    private app.bolivia.swing.JCTextField jCTextField23;
    private app.bolivia.swing.JCTextField jCTextField24;
    private app.bolivia.swing.JCTextField jCTextField25;
    private app.bolivia.swing.JCTextField jCTextField26;
    private app.bolivia.swing.JCTextField jCTextField27;
    private app.bolivia.swing.JCTextField jCTextField28;
    private app.bolivia.swing.JCTextField jCTextField29;
    private app.bolivia.swing.JCTextField jCTextField30;
    private app.bolivia.swing.JCTextField jCTextField31;
    private app.bolivia.swing.JCTextField jCTextField32;
    private app.bolivia.swing.JCTextField jCTextField33;
    private app.bolivia.swing.JCTextField jCTextField34;
    private app.bolivia.swing.JCTextField jCTextField35;
    private app.bolivia.swing.JCTextField jCTextField36;
    private app.bolivia.swing.JCTextField jCTextField37;
    private app.bolivia.swing.JCTextField jCTextField38;
    private app.bolivia.swing.JCTextField jCTextField39;
    private app.bolivia.swing.JCTextField jCTextField40;
    private app.bolivia.swing.JCTextField jCTextField41;
    private app.bolivia.swing.JCTextField jCTextField42;
    private app.bolivia.swing.JCTextField jCTextField6;
    private app.bolivia.swing.JCTextField jCTextField7;
    private app.bolivia.swing.JCTextField jCTextField8;
    private app.bolivia.swing.JCTextField jCTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private necesario.RSMaterialButtonCircle rSMaterialButtonCircle2;
    private app.bolivia.swing.JCTextField txt_contact;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
